name: "publish"

on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch:

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest"
            arch: "aarch64-apple-darwin"
            generateUpdater: true
          - platform: "macos-latest"
            arch: "x86_64-apple-darwin"
            generateUpdater: false
          - platform: "ubuntu-24.04"
            arch: ""
            generateUpdater: false
          - platform: "windows-latest"
            arch: ""
            generateUpdater: false

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Install pnpm + deps
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 10
          run_install: true

      - name: Use Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.arch != '' && matrix.arch || '' }}

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-24.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - uses: tauri-apps/tauri-action@action-v0.5.20
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: v__VERSION__
          releaseName: "v__VERSION__"
          releaseBody: "Note: macOS builds are not signed. To run the app, after moving it to Applications folder, run: `xattr -c /Applications/tauri-app.app`"
          releaseDraft: false
          prerelease: false
          args: ${{ matrix.arch != '' && format('--target {0}', matrix.arch) || '' }}

      - name: Upload latest.json as artifact
        if: matrix.generateUpdater == true
        uses: actions/upload-artifact@v4
        with:
          name: updater-artifact
          path: |
            src-tauri/target/**/bundle/updater/latest.json
          if-no-files-found: error

  push-updater:
    name: Push updater file to updater branch
    needs: publish-tauri
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Download latest.json artifact
        uses: actions/download-artifact@v4
        with:
          name: updater-artifact
          path: src-tauri/updater/

      - name: Setup Git config
        run: |
          git config user.name "lin52025iq"
          git config user.email "lin52025iq@github.com"

      - name: Fetch updater branch
        run: |
          git fetch origin updater || true
          git checkout -B updater origin/updater || git checkout -b updater

      - name: Commit and push latest.json
        run: |
          git add src-tauri/updater/latest.json
          git commit -m "chore: update latest.json for ${{ github.ref_name }}" || echo "No changes to commit"
          git push origin HEAD:updater
